finish the translation of package container and sort
studygolang/go pull request #20
Opened 2020-12-07 14:52 UTC by bqdong

This PR will be imported into Gerrit with the title and first
comment (this text) used to generate the subject and body of
the Gerrit change.

**Please ensure you adhere to every item in this list.**

More info can be found at https://github.com/golang/go/wiki/CommitMessage

+ The PR title is formatted as follows: `net/http: frob the quux before blarfing`
  + The package name goes before the colon
  + The part after the colon uses the verb tense + phrase that completes the blank in,
    "This change modifies Go to ___________"
  + Lowercase verb after the colon
  + No trailing period
  + Keep the title as short as possible. ideally under 76 characters or shorter
+ No Markdown
+ The first PR comment (this one) is wrapped at 76 characters, unless it's
  really needed (ASCII art, table, or long link)
+ If there is a corresponding issue, add either `Fixes #1234` or `Updates #1234`
  (the latter if this is not a complete fix) to this comment
+ If referring to a repo other than `golang/go` you can use the
  `owner/repo#issue_number` syntax: `Fixes golang/tools#1234`
+ We do not use Signed-off-by lines in Go. Please don't add them.
  Our Gerrit server & GitHub bots enforce CLA compliance instead.
+ Delete these instructions once you have read and applied them

2020-12-29 02:36 UTC, polaris1119 requested changes

2020-12-29 02:36 UTC, polaris1119 commented on src/container/heap/example_pq_test.go
> +	// 我们希望 Pop 给我们最高而非最低的优先级，因此我们使用在这里使用大于。
多了个 “使用”

2020-12-29 02:36 UTC, polaris1119 commented on src/container/heap/heap.go
> +// n = h.Len() 处的复杂度是 O(log n)。
这段有些问题。invariants 译为约束性如何？
该句的大概意思：一个堆在使用任何堆操作之前应先初始化。Init函数对于堆的约束性是幂等的（多次执行无意义），并可能在任何时候堆的约束性被破坏时被调用。

你看如何调整下

2020-12-29 02:36 UTC, polaris1119 commented on src/container/heap/heap.go
> +// n = h.Len() 处的复杂度是 O(log n)。
建议改为：复杂度是 O(log n)，n = h.Len() 

下同

怎么感觉原文 大 O 是 0？

2020-12-29 02:36 UTC, polaris1119 commented on src/container/list/list.go
>  // lazyInit lazily initializes a zero List value.
这一句英文没删除

2020-12-29 11:49 UTC, bqdong commented on src/container/heap/heap.go
> +// n = h.Len() 处的复杂度是 O(log n)。
这一段有些不太会翻译，就按照你说的那个翻译，行吗？

2020-12-29 11:51 UTC, bqdong commented on src/container/list/list.go
>  // lazyInit lazily initializes a zero List value.
这个函数不出现在文档里，就可以不用翻译了，我把翻译删掉

2020-12-29 11:54 UTC, bqdong commented on src/container/heap/heap.go
> +// n = h.Len() 处的复杂度是 O(log n)。
我看了一下，原文是 O ，不是 0 (零）。我把翻译调整一下

2021-02-18 07:43 UTC, darcyaf commented on src/container/list/list.go
> +// lazyInit 惰性地初始化一个零列表值。
```suggestion
```

2021-02-18 07:45 UTC, merged